#!/bin/sh

case "$1" in
	"--version")
		pkg-config --modversion gdlib
		;;
	"--majorversion")
		pkg-config --modversion gdlib | awk -F"." '{print $1}'
		;;
	"--minorversion")
		pkg-config --modversion gdlib | awk -F"." '{print $2}'
		;;
	"--revision")
		pkg-config --modversion gdlib | awk -F"." '{print $3}'
		;;
	"--includes")
		pkg-config --variable=includedir gdlib
		;;
	"--ldflags")
		echo "-L`pkg-config --variable=libdir gdlib`"
		;;
	"--cflags")
		echo "-I`pkg-config --variable=includedir gdlib`"
		;;
	"--libs")
		pkg-config --libs gdlib
		;;
	*)
		echo
		;;
esac
